blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/james-elicx/package-manager-manager/discussions/new?category=feature-request
    about: Feature requests should be opened as discussions
